config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  root 'welcome#index'
  resources :activities, only: [:index, :show]
  resources :orders, only: [:new, :create, :show]
  get 'my_orders', to: 'users#my_orders'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  # relations
  belongs_to :user
  has_many :orders
  
  # validations
  validates_presence_of :title, :description, :user
  
  # scopes
    scope :has_tickets_left, -> { where("participants < max_participants") }
    scope :order_by_date, -> { order(:date)}
  
  
  def amount_of_tickets_left
    max_participants - participants
  end
  
  def update_participants_count(number_of_participants)
    self.participants = self.participants + number_of_participants
    self.save
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
  
  # need to validate wheter or not order can or canot be booked depending on tickets left
  validate :exceed_tickets_limit
  
  def exceed_tickets_limit
    if self.amount_of_tickets > self.activity.amount_of_tickets_left
      self.errors.add(:amount_of_tickets, "There is not enough tickets left. please try again")
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # relations
  has_many :activities
  has_many :orders
  
  # validations
  validates_presence_of :name

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.has_tickets_left.order_by_date.paginate(page: params[:page], per_page: 6)
  end
  
  def show
    @activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: :create
  
  def create
    @order = Order.new(order_params)
    @activity = Activity.find(params[:activity_id])
    @order.user_id = current_user.id if current_user.present?
    @order.activity_id =  @activity.id if @activity.present?
    @order.total_price = @order.amount_of_tickets * @activity.price
    if @order.save
      @activity.update_participants_count(@order.amount_of_tickets)
      redirect_to order_path(@order)
    else
      flash[:danger] = "Something went wrong, please try again"
      redirect_to activity_path(@activity)
    end
  end
  
  def show
    @order = Order.find(params[:id])
    @activity = @order.activity
  end
    
  private
  
  def order_params
    params.require(:order).permit(:amount_of_tickets)
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def my_orders
    @user = current_user
    @user_orders = @user.orders.joins(:activity).order("activities.date ASC")
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/_activity.html.erb
  <div class="col-xs-4 activity-box">
    <div class="well well-lg">
      <h3 class="activity-title"><%= link_to activity.title, activity_path(activity) %></h3>
      <hr class="line-breaker">
      <div class="activity-date">
        <%= activity.date %>
      </div>
      <hr class="line-breaker">
      <div class="activity-price">
        <p><%= activity.price %> ILS per ticket</p>
      </div>
    </div>
  </div>

app/views/activities/index.html.erb
<div class="center">
  <%= will_paginate %>
</div>
<div class="row">
<%= render @activities %>
</div>
<div class="center">
  <%= will_paginate %>
</div>

app/views/activities/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 activity-box">
    <div class="well well-lg">
      <div class="activity-title">
        <h1><%= @activity.title %></h1>
        <hr>
      </div>
      <div class="activity-details">
        <ul class="listing no-padding">
          <li><%= @activity.user.name  %></li>
          <hr>
          <li><%= @activity.description %></li>
          <li><%= @activity.max_participants %></i
        </ul>
      </div>
    </div>
  </div>
  
  <%= render 'orders/form', activity: @activity %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Mini Funzing", root_path, class: "navbar-brand"%>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Activities", activities_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Orders", my_orders_path  %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-right col-md-4">
        <li class="col-md-8 user-name text-right">
          <i class="fa fa-user"></i>
          <%= current_user.present? ? current_user.name : "Anonymous" %>
        </li>
        <li class="col-md-4">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, class: "btn btn-xs logout", method: :delete %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-xs btn-success"  unless user_signed_in? %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Funzing" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navigation'%>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/orders/_form.html.erb
<div class="booking-section col-xs-12 col-sm-4">
  <div class="well">
  <%= form_for Order.new do |f| %>
      <%= hidden_field_tag :activity_id, @activity.id %>
      <div class="form-group">
        <div class="activity-date center form-spacing">
          <%= @activity.date %>
        </div>
        <div class="activity-price form-spacing">
          <%= @activity.price %> ILS per ticket
        </div>
        <div>
          <%= f.label "How many tickets?" %>
        </div>
        <div class="form-padding">
          <%= f.select(:amount_of_tickets, (1..@activity.amount_of_tickets_left)) %>
        </div>
        <div class="col-xs-12 center form-spacing">
          <%= f.submit "Book now", class: "book-now-btn" %>
        </div>
      </div>
  <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="row">
  <div class="well col-xs-6">
    <h3># Order <%= @order.id %></h3>
    <h2><%=@activity.title %></h2>
    <hr>
    <p><%=@activity.user.name %></p>
    <hr>
    <p><%= DateTime.now %></p>
    <p><%= @order.amount_of_tickets%> tickets</p>
    <p>Total price: שח<%= @order.total_price%></p>
  </div>
</div>

app/views/users/my_orders.html.erb
<div class="row">
  <div class="col-xs-6 well">
    <h1>My Orders</h1>
    <% @user_orders.each do |order| %>
      <hr>
      <p># Order <%= order.id %> - <%= order.activity.title %> - Date: <%= order.activity.date %></p>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to funzing app</h1>
<% if user_signed_in? %>
 <%= link_to "Logout", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete %>
<% else %>
 <%= link_to "Login", new_user_session_path, class: "btn btn-xs btn-success"  unless user_signed_in? %>
<% end%>